services:
  mysql:
    image: mysql:8.0
    container_name: crud-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: crud_db
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local